import marimo

__generated_with = "0.24.2"
app = marimo.App(width="medium", app_title="18BIG S1 — SQL basics")


@app.cell
def _():
    import duckdb
    import marimo as mo

    from eshop.config import settings

    return duckdb, mo, settings


@app.cell
def _(mo):
    mo.md(r"""
    # Session 1 — SQL basics, live

    Six core SQL building blocks, each as **task → query → result**. Every query below runs
    directly against the raw e-shop sources generated by `uv run eshop datagen` — no server,
    just files (`data/raw/*.csv`) and a SQLite database (`data/raw/shop.sqlite`).

    Edit a query and re-run its cell any time — that's the point of a live notebook.
    """)
    return


@app.cell
def _(duckdb, mo, settings):
    mo.md(
        r"""
    ### Setup: point DuckDB at the raw files

    DuckDB reads CSV and SQLite **directly** — no import step, no separate database server.
    We wrap each source in a `VIEW` so the rest of this notebook can write plain table names.
    """
    )

    con = duckdb.connect()
    con.execute(f"CREATE VIEW customers AS SELECT * FROM read_csv_auto('{settings.raw_dir / 'customers.csv'}')")
    con.execute(f"CREATE VIEW products  AS SELECT * FROM read_csv_auto('{settings.raw_dir / 'products.csv'}')")
    con.execute(f"CREATE VIEW payments  AS SELECT * FROM read_csv_auto('{settings.raw_dir / 'payments.csv'}')")
    con.execute(f"CREATE VIEW orders      AS SELECT * FROM sqlite_scan('{settings.source_db}', 'orders')")
    con.execute(f"CREATE VIEW order_items AS SELECT * FROM sqlite_scan('{settings.source_db}', 'order_items')")
    return (con,)


@app.cell
def _(mo):
    mo.md(r"""
    ## 1. SELECT columns & FROM

    **Task:** list each customer's name, city and signup date — newest signups first.
    """)
    return


@app.cell
def _(con, customers, mo):
    _df = mo.sql(
        f"""
        SELECT *
        FROM customers
        """,
        engine=con
    )
    return


@app.cell
def _(con, customers, mo):
    task1 = mo.sql(
        f"""
        SELECT name, city, signup_date
        FROM customers
        ORDER BY signup_date DESC
        LIMIT 10
        """,
        engine=con
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 2. Filtering rows: WHERE

    **Task:** which orders are still `NEW` (placed, but not yet paid)?
    """)
    return


@app.cell
def _(con, mo, orders):
    task2 = mo.sql(
        f"""
        SELECT order_id, customer_id, order_ts, status
        FROM orders
        WHERE status = 'NEW'
        ORDER BY order_ts
        LIMIT 10
        """,
        engine=con
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 3. Combining tables: JOIN

    **Task:** for each order, show the customer's name next to the order status —
    that information lives in two different tables.
    """)
    return


@app.cell
def _(con, customers, mo, orders):
    task3 = mo.sql(
        f"""
        SELECT o.order_id, c.name AS customer, o.status
        FROM orders o
        JOIN customers c ON o.customer_id = c.customer_id
        ORDER BY o.order_id
        LIMIT 10
        """,
        engine=con
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 4. Aggregation & GROUP BY

    **Task:** how many orders does each customer have? Rank the most active customers first.

    `GROUP BY` collapses many rows into one per group — every selected column must either be
    in `GROUP BY` or wrapped in an aggregate like `count(*)`.
    """)
    return


@app.cell
def _(con, mo, orders):
    task4 = mo.sql(
        f"""
        SELECT customer_id, count(*) AS n_orders
        FROM orders
        GROUP BY customer_id
        ORDER BY n_orders DESC
        LIMIT 10
        """,
        engine=con
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 5. Window functions: LAG & LEAD

    **Task:** for each customer, line up every order next to that same customer's
    *previous* and *next* order timestamp — without collapsing any rows.

    Unlike `GROUP BY`, a window function (`OVER (...)`) keeps one row per input row and adds a
    value computed from *neighboring* rows in the same partition.
    """)
    return


@app.cell
def _(con, mo, orders):
    task5 = mo.sql(
        f"""
        SELECT
            customer_id,
            order_id,
            order_ts,
            lag(order_ts)  OVER (PARTITION BY customer_id ORDER BY order_ts) AS prev_order_ts,
            lead(order_ts) OVER (PARTITION BY customer_id ORDER BY order_ts) AS next_order_ts
        FROM orders
        ORDER BY customer_id, order_ts
        LIMIT 15
        """,
        engine=con
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 6. CTE: `WITH ...`

    **Task:** compute each order's total value, then average those totals — in two clean
    steps instead of one nested subquery.

    A CTE (`WITH name AS (...)`) names an intermediate query so the final `SELECT` can read
    like a sentence: "using `per_order`, compute the average."
    """)
    return


@app.cell
def _(con, mo, order_items):
    task6 = mo.sql(
        f"""
        WITH per_order AS (
            SELECT order_id, SUM(qty * unit_price) AS order_total
            FROM order_items
            GROUP BY order_id
        )
        SELECT round(avg(order_total), 2) AS avg_order_value
        FROM per_order
        """,
        engine=con
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ---

    ### Now on your own

    Same six ideas, new questions: fill in the `# TODO`s in
    `sessions/01-foundations/exercise/explore.py`.
    """)
    return


if __name__ == "__main__":
    app.run()
