name: eshop_dbt
version: "1.0"
config-version: 2

profile: eshop

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  eshop_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
